version: '2'

networks:
    dkfbasel:
        external: true

services:

    api:
        image: dkfbasel/hot-reload-go:1.8.1
        networks: [dkfbasel]
        ports:
            - 3002:80
        volumes:
            - ./backend:/app
            - ../build/templates:/tmp/templates

        environment:
            - PROJECT=bitbucket.org/dkfbasel/scratch/src/backend
            - HOST=0.0.0.0:80
            - CMD=build

    frontend:
        image: dkfbasel/hot-reload-webpack:3.1.0
        networks: [dkfbasel]
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app
            - ../build/public:/tmp/public
        environment:
            - COMMAND=npm run dev
